Update tmate.yml

diff --git a/.github/workflows/tmate.yml b/.github/workflows/tmate.yml
--- a/.github/workflows/tmate.yml
+++ b/.github/workflows/tmate.yml
@@ -33,10 +33,19 @@ jobs:
 
       - name: 🧰 Install dependencies
         run: |
-          sudo apt update -y
-          sudo apt install -y unzip curl jq git docker.io tmate || true
-          docker --version
-          tmate -V
+         sudo apt-get update -y
+         sudo apt-get install -y unzip jq curl git || true
+         sudo apt-get remove -y containerd containerd.io || true
+         curl -fsSL https://get.docker.com | sh
+         docker --version
+         if ! command -v tmate >/dev/null 2>&1; then
+         sudo apt-get install -y software-properties-common
+         sudo add-apt-repository -y ppa:tmate.io/archive
+         sudo apt-get update
+         sudo apt-get install -y tmate
+         fi
+
+         tmate -V || echo "tmate installation failed"
 
       - name: 🐬 Start MySQL in Docker
         run: |
